### ISSUE TITLE
crash on campaign launch, 1.4 with other mods enabled (no crash w/o BL tweaks)

### ISSUE THREAD

**Issue by kreamy91** [mipen/BannerlordTweaks#119]
Stack trace:

at BannerlordTweaks.Patches.DefaultBuildingTypesPatch.Postfix(BuildingType ____buildingCastleTrainingFields, BuildingType ____buildingCastleGranary, BuildingType ____buildingCastleGardens, BuildingType ____buildingCastleMilitiaBarracks)

at TaleWorlds.CampaignSystem.Campaign.InitializeDefaultCampaignObjects()

at TaleWorlds.CampaignSystem.Campaign.OnCampaignStart(CampaignGameStarter gameStarter)

at TaleWorlds.CampaignSystem.Campaign.OnInitialize()

at TaleWorlds.CampaignSystem.Campaign.DoLoadingForGameType(GameTypeLoadingStates gameTypeLoadingState, GameTypeLoadingStates& nextState)

at StoryMode.CampaignStoryMode.DoLoadingForGameType(GameTypeLoadingStates gameTypeLoadingState, GameTypeLoadingStates& nextState)

at TaleWorlds.Core.GameType.DoLoadingForGameType()

at StoryMode.StoryModeGameManager.DoLoadingForGameManager(GameManagerLoadingSteps gameManagerLoadingStep, GameManagerLoadingSteps& nextStep)

at TaleWorlds.Core.GameManagerBase.DoLoadingForGameManager()

at TaleWorlds.MountAndBlade.GameLoadingState.OnTick(Single dt)

at TaleWorlds.Core.GameStateManager.OnTick(Single dt)

at DMD<DMD<OnApplicationTick_Patch1>?12662112::OnApplicationTick_Patch1>(Module this, Single dt)
erro= ok

**running mods:**
Aragas Save
Army Arrow Counter
Ask Lords Location
Autoblocker 1.0.7
Autotrader 
Bannerlord tweaks (1.3.6)
Bearmybanner 
Character Import
Control Allies After Death
Defection Overhaul
Diplomacy Fixes
Dismemberment
Dontsmeltlocked
Equipbestitem
Fighting together relation
Fixedlauncher
Freeplay
ImprovedCombat AI
Improved garrisons (3.1.0.6)
Leaveonclick
Modlib beta 1.4
Party AI Overhaul
Party Screen enhancemenst
Persistentlock
Righteous Exectuions
RTS Camera
Settlement Icons
Shieldsblockon back
Show settlement
Sound the Alaram
Troop collision fix
Unblockdlls
viewallwars
xoberax banks, cut, friendlyfire, pressVyell, terriblevoices, training field

**Comment by mipen** [comment]
What is the error that is happening?
I think you might have the incorrect version of the mod. Make sure you are using the 1.4 version of the mod. If the error is still happening, turn off the castle buildings tweaks, as these are the ones causing the exception

**Comment by kreamy91** [comment]
> What is the error that is happening?
> I think you might have the incorrect version of the mod. Make sure you are using the 1.4 version of the mod. If the error is still happening, turn off the castle buildings tweaks, as these are the ones causing the exception

disabled xoberax's training fields. works well now.
