### ISSUE TITLE
ModLib Issue when starting the game

### ISSUE THREAD

**Issue by FallenShama** [mipen/BannerlordTweaks#70]
When trying to use the recent version of BannerlordTweaks the game returns an error.

Error occurred during loading files

An error occurred whilst trying to load files for module:
zzBannerlordTweaks

Exception:
An error occured while FileDatabase was trying to load all files for module zzBannerlordTweaks

Execption:
An error occured whilst loading file
../../Modules\zzBannerlordTweaks\ModuleData\Loadables\Settings.ModLibSettings.xml

Exeception:
Unable to find Type ModLib.Settings, ModLib

Stack trace:
at ModLib.FileDatabase.LoadAllFiles(String moduleName)
at ModLib.FileDatabase.Initialise(String moduleFolderName)

I have ModLib downloaded an in my Bannerlord module folder. I have redownloaded it again today. I have used vanilla and "Alternative Launcher". Ordered ModLib underneath the vanilla mods and put BannerlordTweaks below it. Both launchers return the same error. What am I missing here? I'm not really firm with modding stuff so I don't really know what else I could give you here to make the issue more fixable... Thank you for your help in advance!

EDIT: I'm not on the beta branch and using the newest e1.1.2 version of the game.

**Comment by FallenShama** [comment]
Okay, this just fixed itself... I deleted all files related to ModLib and BannerlordTweaks, redownloaded it, extracted all files again and now its working...
